# Generated by Django 4.2.1 on 2023-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LC', 'Location'), ('ZD', 'Zordiac'), ('NS', 'Native Species'), ('FE', 'Festivals'), ('OT', 'Other')], max_length=2),
        ),
    ]
