# Generated by Django 4.2.1 on 2023-07-14 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='ordered_date',
        ),
    ]
