# Generated by Django 4.2.1 on 2023-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounter_price',
            new_name='discounted_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('CH', 'Cheese'), ('BU', 'Butter'), ('ML', 'Milk'), ('OT', 'Other')], max_length=2),
        ),
    ]
