# Generated by Django 4.2.1 on 2023-07-14 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Planted', 'Planted'), ('On The Way', 'On The Way'), ('Pending', 'Pending'), ('Growing', 'Growing'), ('Diseased', 'Diseased'), ('Harvested', 'Harvested')], default='Pending', max_length=50)),
                ('planted_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('photographic_documentation', models.ImageField(upload_to='product')),
                ('maintenance', models.CharField(choices=[('Watering', 'Watering'), ('Pruning', 'Pruning'), ('Fertilizing', 'Fertilizing'), ('Mulching', 'Mulching'), ('Weeding', 'Weeding'), ('Pest Control', 'Pest Control')], default='Pending', max_length=100)),
                ('soil_assessment', models.CharField(choices=[('Soil Testing', 'Soil Testing'), ('Composting', 'Composting'), ('Aerating Soil', 'Aerating Soil'), ('pH Adjustment', 'pH Adjustment'), ('Soil Moisture Monitoring', 'Soil Moisture Monitoring'), ('Soil Drainage Improvement', 'Soil Drainage Improvement')], default='Pending', max_length=100)),
                ('products', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
